// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    seed: 'tsx ./prisma/seed.ts',
  },
  datasource: {
    // Prisma v7 reads the database connection string here!
    url: "postgresql://dashboard_admin:secure_local_password@localhost:5432/dashboard_dev",
  },
});
